script:
- |
  git config user.name "lc-education-ci"
  git config user.email "education+ci@launchcode.org"
  git remote remove origin
  git remote add origin https://$GITHUB_API_KEY@github.com/LaunchCodeEducation/intro-to-professional-web-dev-wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/LaunchCodeEducation/intro-to-professional-web-dev.wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
    secure: h4xWjNo/3zypvHvqA+ujrxVQEXAZZME5utQJu11udVhpYLEH0GwD+tb2jsM8YRNM3ZjA0XjnVylrw1Hrr8yPh8fG8/KVrkMsGW6uTSfWoUc9o0ld8vQdjo5vNQuEwA9/XMYiIbT5rDPR1nBCR2JfYx4wsRnnG5Zz+Z8Px++1G8iIrnFhUHPIomv+QwFFheiKfRpoKEM76JBcJHaOa/1qtc3+NifvAvPRI6aSDIf9fGUAGA0yYU0m+o4OdwnAf4cUkZktawm4Kk0ErfkW0tzpA2NXvFYwh+9Hvm2bq1bJKNhsM6WQ7S+8yS6B7/cBxxvvID9Bmq5BZSNC+GJxZWvi7fMRBUE2tC5DZreGTgdB2oIsgjtq0SOcOtNrWPm3R62ECJxi9/ACugxHfSANC44zPH5r0YNTQVibFfJqVd24rkcPKAfMg+g32YLxfDqWLjeGm1Z1myTwoeVn200Aw4oMh4JrVSoYXUHYbUpFgIqhfoRv7c1HAquV9CONpLpbVGf1oKSybamU7FDeDJjUyDX76bbQMaXeqw2azGHShQrfsc2+ljyvp9JZEdMGL3WdZ80nLTE8TM/cawMsisUUka6a11FgXhT2daIZYPQcPNA6ccE7fGwsN+qQpmkN3sCcP9FxdqoC54SfvzOBugiFb096qHvWROwBo4/hIhPSS5zZOGk=
